"""update project model

Revision ID: c5bed67d8e0e
Revises: 949fb9f65373
Create Date: 2024-10-16 10:48:03.687754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5bed67d8e0e'
down_revision: Union[str, None] = '949fb9f65373'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('business_category_id', sa.Integer(), nullable=True))
    op.alter_column('projects', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'projects', 'business_categories', ['business_category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.alter_column('projects', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('projects', 'business_category_id')
    # ### end Alembic commands ###
